<?php
require_once 'config.php';require_auth();ensure_schema();$pageTitle='Panel general';$pdo=db();
$rows=$pdo->query('SELECT current_status,COUNT(*) total FROM work_orders GROUP BY current_status')->fetchAll();$counts=[];foreach($rows as $r)$counts[$r['current_status']]=(int)$r['total'];
$open=array_diff(STATUSES,['Entregada','Cancelada']);$ph=implode(',',array_fill(0,count($open),'?'));$st=$pdo->prepare("SELECT COUNT(*) FROM work_orders WHERE current_status IN ($ph)");$st->execute(array_values($open));$openOrders=(int)$st->fetchColumn();
$today=(int)$pdo->query('SELECT COUNT(*) FROM work_orders WHERE DATE(created_at)=CURRENT_DATE')->fetchColumn();$ready=(int)($counts['Lista para retirar']??0);$low=(int)$pdo->query('SELECT COUNT(*) FROM parts WHERE active=1 AND stock<=min_stock')->fetchColumn();
$orders=$pdo->query('SELECT wo.*,c.name client_name,v.brand,v.model,v.plate FROM work_orders wo JOIN clients c ON c.id=wo.client_id JOIN vehicles v ON v.id=wo.vehicle_id ORDER BY wo.updated_at DESC LIMIT 8')->fetchAll();
$alerts=$pdo->query('SELECT id,name,sku,stock,min_stock FROM parts WHERE active=1 AND stock<=min_stock ORDER BY stock,name LIMIT 6')->fetchAll();include 'partials/header.php';?>
<div class="grid">
<section class="card hero-card span12"><div><span class="badge">Resumen operativo</span><h1>Buen día, <?=h(auth()['name'])?></h1><p>Controlá órdenes, clientes, motos y stock desde un único lugar.</p></div><div class="hero-actions"><a class="btn btn-primary" href="order_new.php">Nueva orden</a><a class="btn" href="parts.php">Gestionar stock</a></div></section>
<?php foreach([['Órdenes activas',$openOrders,'Trabajos sin entregar'],['Ingresos de hoy',$today,date_ar(date('Y-m-d'))],['Listas para retirar',$ready,'Pendientes de entrega'],['Alertas de stock',$low,'Mínimo o agotado']] as $k):?><article class="card kpi-card span3"><span class="kpi-label"><?=h($k[0])?></span><div class="kpi"><?=$k[1]?></div><div class="kpi-foot"><?=h($k[2])?></div></article><?php endforeach;?>
<section class="card span8"><div class="card-header"><div><h2>Últimas órdenes</h2><p>Actividad reciente del taller</p></div><a class="btn btn-sm" href="orders.php">Ver todas</a></div><?php if($orders):?><div class="table-wrap responsive"><table><thead><tr><th>Orden</th><th>Cliente y moto</th><th>Estado</th><th>Actualizada</th><th></th></tr></thead><tbody><?php foreach($orders as $o):?><tr><td class="primary-cell"><strong><?=h($o['code'])?></strong><br><small class="muted"><?=h(ucfirst($o['priority']))?></small></td><td data-label="Cliente y moto"><strong><?=h($o['client_name'])?></strong><br><small class="muted"><?=h($o['brand'].' '.$o['model'].' · '.$o['plate'])?></small></td><td data-label="Estado"><span class="status <?=h(status_tone($o['current_status']))?>"><?=h($o['current_status'])?></span></td><td data-label="Actualizada"><?=h(date_ar($o['updated_at'],true))?></td><td data-label="Acción"><a class="btn btn-sm" href="order_view.php?id=<?=(int)$o['id']?>">Abrir</a></td></tr><?php endforeach;?></tbody></table></div><?php else:?><div class="empty-state"><div><div class="empty-icon">01</div><h2>No hay órdenes todavía</h2><a class="btn btn-primary" href="order_new.php">Crear orden</a></div></div><?php endif;?></section>
<aside class="card span4"><div class="card-header"><div><h2>Stock crítico</h2><p>Requiere reposición</p></div></div><?php if($alerts):?><div class="timeline"><?php foreach($alerts as $p):?><div class="event"><strong><?=h($p['name'])?></strong><small class="muted"><?=h($p['sku']?:'Sin SKU')?></small><p>Disponible: <b class="<?=(float)$p['stock']<=0?'stock-zero':'stock-low'?>"><?=h($p['stock'])?></b> · Mínimo: <?=h($p['min_stock'])?></p></div><?php endforeach;?></div><a class="btn btn-block" href="parts.php?stock=low">Revisar inventario</a><?php else:?><div class="empty-state"><div><div class="empty-icon">✓</div><h2>Stock controlado</h2><p class="muted">No hay productos bajo el mínimo.</p></div></div><?php endif;?></aside>
</div><?php include 'partials/footer.php';?>
