<?php
require_once 'config.php';require_auth();ensure_schema();$pageTitle='Nueva orden';$pdo=db();$error=null;
$clients=$pdo->query('SELECT id,name,phone,dni FROM clients WHERE active=1 ORDER BY name')->fetchAll();$vehicles=$pdo->query('SELECT id,client_id,brand,model,plate FROM vehicles WHERE active=1 ORDER BY brand,model')->fetchAll();
if(is_post()){
 try{verify_csrf();$cm=post('client_mode','new')==='existing'?'existing':'new';$vm=post('vehicle_mode','new')==='existing'?'existing':'new';$problem=trim((string)post('problem_reported'));$priority=in_array(post('priority'),PRIORITIES,true)?post('priority'):'normal';if($problem==='')throw new RuntimeException('Ingresá el problema declarado por el cliente.');$pdo->beginTransaction();
  if($cm==='existing'){$clientId=(int)post('client_id');$st=$pdo->prepare('SELECT id FROM clients WHERE id=? AND active=1');$st->execute([$clientId]);if(!$st->fetch())throw new RuntimeException('Seleccioná un cliente válido.');}
  else{$name=clean_text(post('client_name'));$phone=clean_text(post('phone'));if($name===''||$phone==='')throw new RuntimeException('Nombre y teléfono son obligatorios.');$st=$pdo->prepare('INSERT INTO clients(name,phone,email,dni,address,notes) VALUES(?,?,?,?,?,?)');$st->execute([$name,$phone,nullable_text(post('email')),nullable_text(post('dni')),nullable_text(post('address')),nullable_text(post('client_notes'))]);$clientId=(int)$pdo->lastInsertId();$vm='new';}
  if($vm==='existing'){$vehicleId=(int)post('vehicle_id');$st=$pdo->prepare('SELECT id FROM vehicles WHERE id=? AND client_id=? AND active=1');$st->execute([$vehicleId,$clientId]);if(!$st->fetch())throw new RuntimeException('Seleccioná una moto válida.');}
  else{$brand=clean_text(post('brand'));$model=clean_text(post('model'));$plate=upper_identifier(post('plate'));$engine=upper_identifier(post('engine_number'));$chassis=upper_identifier(post('chassis_number'));if($brand===''||$model===''||$plate===''||$engine===''||$chassis==='')throw new RuntimeException('Marca, modelo, patente, número de motor y número de chasis son obligatorios.');$st=$pdo->prepare('SELECT id FROM vehicles WHERE active=1 AND (plate=? OR engine_number=? OR chassis_number=?) LIMIT 1');$st->execute([$plate,$engine,$chassis]);if($st->fetch())throw new RuntimeException('Ya existe una moto activa con la misma patente, motor o chasis.');$st=$pdo->prepare('INSERT INTO vehicles(client_id,type,brand,model,plate,year,cc,color,engine_number,chassis_number,km) VALUES(?,?,?,?,?,?,?,?,?,?,?)');$st->execute([$clientId,clean_text(post('type'))?:'Moto',$brand,$model,$plate,nullable_text(post('year')),nullable_text(post('cc')),nullable_text(post('color')),$engine,$chassis,int_value(post('km'))]);$vehicleId=(int)$pdo->lastInsertId();}
  $code=order_code();$tok=token();$st=$pdo->prepare('INSERT INTO work_orders(code,client_id,vehicle_id,mechanic_id,problem_reported,priority,estimated_delivery,public_token) VALUES(?,?,?,?,?,?,?,?)');$st->execute([$code,$clientId,$vehicleId,auth()['id'],$problem,$priority,nullable_text(post('estimated_delivery')),$tok]);$oid=(int)$pdo->lastInsertId();$msg='Tu moto ingresó a '.app_name().' con la orden '.$code.'. Ya podés consultar el seguimiento.';$st=$pdo->prepare('INSERT INTO order_updates(order_id,user_id,status,internal_message,client_message,visible_client,notify_client) VALUES(?,?,?,?,?,1,0)');$st->execute([$oid,auth()['id'],'Ingresada','Orden creada en recepción',$msg]);$pdo->commit();flash('success',"Orden {$code} creada correctamente.");redirect('order_view.php?id='.$oid);
 }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$error=$e->getMessage();}
}
include 'partials/header.php';?>
<div class="page-head"><div class="page-head-copy"><h1>Nueva orden de trabajo</h1><p>Registrá cliente, moto y motivo de ingreso. Patente, motor y chasis se guardan en mayúsculas.</p></div></div><?php if($error):?><div class="alert alert-error"><span><?=h($error)?></span></div><?php endif;?>
<form method="post" class="grid"><?=csrf_field()?>
<section class="card span6"><div class="card-header"><div><h2>1. Cliente</h2><p>Usá uno existente o cargá uno nuevo.</p></div></div><div class="segmented"><label><input type="radio" name="client_mode" value="new" <?=post('client_mode','new')!=='existing'?'checked':''?>><span>Cliente nuevo</span></label><label><input type="radio" name="client_mode" value="existing" <?=post('client_mode')==='existing'?'checked':''?>><span>Cliente existente</span></label></div>
<div data-client-mode-panel="new" style="margin-top:18px"><div class="form-grid"><div class="field span6"><label class="required">Nombre completo</label><input name="client_name" data-mode-required="true" value="<?=h(post('client_name'))?>"></div><div class="field span6"><label class="required">Teléfono / WhatsApp</label><input name="phone" data-mode-required="true" value="<?=h(post('phone'))?>"></div><div class="field span6"><label>Email</label><input type="email" name="email" value="<?=h(post('email'))?>"></div><div class="field span6"><label>DNI</label><input name="dni" value="<?=h(post('dni'))?>"></div><div class="field"><label>Dirección</label><input name="address" value="<?=h(post('address'))?>"></div><div class="field"><label>Notas</label><textarea name="client_notes"><?=h(post('client_notes'))?></textarea></div></div></div>
<div data-client-mode-panel="existing" style="margin-top:18px" hidden><div class="field"><label class="required">Seleccionar cliente</label><select name="client_id" id="existingClient" data-mode-required="true"><option value="">Elegí un cliente...</option><?php foreach($clients as $c):?><option value="<?=(int)$c['id']?>" <?=(string)post('client_id')===(string)$c['id']?'selected':''?>><?=h($c['name'].' · '.$c['phone'])?></option><?php endforeach;?></select></div></div></section>
<section class="card span6"><div class="card-header"><div><h2>2. Moto</h2><p>Los identificadores registrales son obligatorios.</p></div></div><div class="segmented"><label><input type="radio" name="vehicle_mode" value="new" <?=post('vehicle_mode','new')!=='existing'?'checked':''?>><span>Moto nueva</span></label><label><input type="radio" name="vehicle_mode" value="existing" <?=post('vehicle_mode')==='existing'?'checked':''?>><span>Ya cargada</span></label></div>
<div data-vehicle-mode-panel="existing" style="margin-top:18px" hidden><div class="field"><label class="required">Moto del cliente</label><select name="vehicle_id" id="existingVehicle" data-vehicle-required="true"><option value="">Elegí una moto...</option><?php foreach($vehicles as $v):?><option value="<?=(int)$v['id']?>" data-client-id="<?=(int)$v['client_id']?>" <?=(string)post('vehicle_id')===(string)$v['id']?'selected':''?>><?=h($v['brand'].' '.$v['model'].' · '.$v['plate'])?></option><?php endforeach;?></select></div></div>
<div data-vehicle-mode-panel="new" style="margin-top:18px"><div class="form-grid"><div class="field span4"><label>Tipo</label><input name="type" value="<?=h(post('type','Moto'))?>"></div><div class="field span4"><label class="required">Marca</label><input name="brand" data-vehicle-required="true" value="<?=h(post('brand'))?>"></div><div class="field span4"><label class="required">Modelo</label><input name="model" data-vehicle-required="true" value="<?=h(post('model'))?>"></div><div class="field span6"><label class="required">Patente</label><input name="plate" data-uppercase data-vehicle-required="true" value="<?=h(post('plate'))?>"><span class="help">Mayúsculas y sin espacios.</span></div><div class="field span3"><label>Año</label><input name="year" value="<?=h(post('year'))?>"></div><div class="field span3"><label>Cilindrada</label><input name="cc" value="<?=h(post('cc'))?>"></div><div class="field span6"><label class="required">Número de motor</label><input name="engine_number" data-uppercase data-vehicle-required="true" value="<?=h(post('engine_number'))?>"></div><div class="field span6"><label class="required">Número de chasis</label><input name="chassis_number" data-uppercase data-vehicle-required="true" value="<?=h(post('chassis_number'))?>"></div><div class="field span6"><label>Color</label><input name="color" value="<?=h(post('color'))?>"></div><div class="field span6"><label>Kilómetros</label><input type="number" min="0" name="km" value="<?=h(post('km'))?>"></div></div></div></section>
<section class="card span12"><div class="card-header"><div><h2>3. Trabajo a realizar</h2><p>Registrá exactamente lo informado al recibir la moto.</p></div></div><div class="form-grid"><div class="field span8"><label class="required">Problema declarado</label><textarea name="problem_reported" required><?=h(post('problem_reported'))?></textarea></div><div class="field span4"><label>Prioridad</label><select name="priority"><?php foreach(PRIORITIES as $p):?><option value="<?=h($p)?>" <?=post('priority','normal')===$p?'selected':''?>><?=h(ucfirst($p))?></option><?php endforeach;?></select><label>Entrega estimada</label><input type="date" name="estimated_delivery" value="<?=h(post('estimated_delivery'))?>"></div><div class="form-actions"><a class="btn" href="orders.php">Cancelar</a><button class="btn btn-primary">Crear orden</button></div></div></section></form><?php include 'partials/footer.php';?>
