<?php
require_once 'config.php'; require_role(['admin','recepcion']); ensure_schema(); $pdo=db(); $pageTitle='Caja'; $error=null;
try{
 if(is_post()){verify_csrf();$a=(string)post('action');
  if($a==='open'){ if(trim((string)post('opening_amount'))==='')throw new RuntimeException('Ingresá el monto inicial de efectivo con el que comienza la caja. Si empezás sin efectivo, escribí 0.');$open=(int)max(0,whole_number_value(post('opening_amount')));$st=$pdo->query("SELECT id FROM cash_sessions WHERE status='abierta' LIMIT 1");if($st->fetch())throw new RuntimeException('Ya existe una caja abierta.');$st=$pdo->prepare('INSERT INTO cash_sessions(opened_by,opening_amount) VALUES(?,?)');$st->execute([auth()['id'],$open]);audit('open','cash_session',(int)$pdo->lastInsertId(),null,['opening_amount'=>$open]);flash('success','Caja abierta.');redirect('cash.php'); }
  if($a==='movement'){ $st=$pdo->query("SELECT * FROM cash_sessions WHERE status='abierta' ORDER BY id DESC LIMIT 1");$session=$st->fetch();if(!$session)throw new RuntimeException('Abrí una caja antes de registrar movimientos.');$amount=whole_number_value(post('amount'));if($amount<=0)throw new RuntimeException('El monto debe ser mayor a cero.');$type=post('type')==='egreso'?'egreso':'ingreso';$method=in_array(post('method'),['efectivo','transferencia','tarjeta','mercadopago','otro'],true)?post('method'):'efectivo';$desc=clean_text(post('description'));if($desc==='')throw new RuntimeException('Ingresá una descripción.');$st=$pdo->prepare('INSERT INTO cash_movements(session_id,user_id,type,amount,method,description) VALUES(?,?,?,?,?,?)');$st->execute([$session['id'],auth()['id'],$type,$amount,$method,$desc]);audit('create','cash_movement',(int)$pdo->lastInsertId(),null,['type'=>$type,'amount'=>$amount,'method'=>$method]);flash('success','Movimiento registrado.');redirect('cash.php'); }
  if($a==='close'){ $id=(int)post('id');$close=whole_number_value(post('closing_amount'));$st=$pdo->prepare('SELECT * FROM cash_sessions WHERE id=? AND status="abierta"');$st->execute([$id]);$session=$st->fetch();if(!$session)throw new RuntimeException('La caja ya está cerrada o no existe.');$pdo->prepare('UPDATE cash_sessions SET status="cerrada",closed_by=?,closed_at=NOW(),closing_amount=?,notes=? WHERE id=?')->execute([auth()['id'],$close,nullable_text(post('notes')),$id]);audit('close','cash_session',$id,$session,['closing_amount'=>$close]);flash('success','Caja cerrada.');redirect('cash.php'); }
 }
}catch(Throwable $e){$error=$e->getMessage();}
$session=$pdo->query("SELECT cs.*,u.name opened_name,cu.name closed_name FROM cash_sessions cs JOIN users u ON u.id=cs.opened_by LEFT JOIN users cu ON cu.id=cs.closed_by WHERE cs.status='abierta' ORDER BY cs.id DESC LIMIT 1")->fetch();
$mov=[];$summary=['ing'=>0,'out'=>0];if($session){$st=$pdo->prepare('SELECT cm.*,u.name user_name FROM cash_movements cm LEFT JOIN users u ON u.id=cm.user_id WHERE session_id=? ORDER BY created_at DESC');$st->execute([$session['id']]);$mov=$st->fetchAll();foreach($mov as $m)$summary[$m['type']==='ingreso'?'ing':'out']+=(int)$m['amount'];}
$history=$pdo->query('SELECT cs.*,u.name opened_name,cu.name closed_name FROM cash_sessions cs JOIN users u ON u.id=cs.opened_by LEFT JOIN users cu ON cu.id=cs.closed_by ORDER BY cs.id DESC LIMIT 15')->fetchAll();include 'partials/header.php';?>
<div class="page-head"><div class="page-head-copy"><h1>Caja</h1><p>Aperturas, ingresos, egresos y cierres.</p></div></div><?php if($error):?><div class="alert alert-error"><span><?=h($error)?></span></div><?php endif;?>
<div class="grid"><section class="card span4"><div class="card-header"><div><h2><?=$session?'Caja abierta':'Abrir caja'?></h2><p><?=$session?'Abierta por '.h($session['opened_name']):'Iniciá la jornada.'?></p></div></div><?php if(!$session):?><form method="post" class="form-grid"><?=csrf_field()?><input type="hidden" name="action" value="open"><div class="field"><label for="openingAmount">Monto inicial de efectivo</label><input id="openingAmount" type="number" name="opening_amount" inputmode="numeric" min="0" step="1" placeholder="Ej.: 50000" required><span class="help">Ingresá cuánto efectivo hay físicamente en la caja al comenzar. Si no hay efectivo, escribí 0.</span></div><button class="btn btn-primary">Abrir caja</button></form><?php else:?><div class="metric-row"><div class="metric-box"><small class="muted">Inicial</small><strong><?=h(money($session['opening_amount']))?></strong></div><div class="metric-box"><small class="muted">Saldo teórico</small><strong><?=h(money((int)$session['opening_amount']+$summary['ing']-$summary['out']))?></strong></div></div><form method="post" class="form-grid" style="margin-top:14px"><?=csrf_field()?><input type="hidden" name="action" value="movement"><div class="field"><label>Tipo</label><select name="type"><option value="ingreso">Ingreso</option><option value="egreso">Egreso</option></select></div><div class="field"><label>Método</label><select name="method"><option value="efectivo">Efectivo</option><option value="transferencia">Transferencia</option><option value="tarjeta">Tarjeta</option><option value="mercadopago">Mercado Pago</option><option value="otro">Otro</option></select></div><div class="field"><label>Monto</label><input name="amount" inputmode="numeric" required></div><div class="field"><label>Descripción</label><input name="description" required></div><button class="btn btn-primary">Registrar movimiento</button></form><form method="post" class="form-grid" style="margin-top:14px" data-confirm="¿Cerrar la caja? Revisá el saldo antes de continuar."><?=csrf_field()?><input type="hidden" name="action" value="close"><input type="hidden" name="id" value="<?=h($session['id'])?>"><div class="field"><label>Efectivo contado al cierre</label><input name="closing_amount" inputmode="numeric" required></div><div class="field"><label>Notas</label><input name="notes"></div><button class="btn btn-danger">Cerrar caja</button></form><?php endif;?></section>
<section class="card span8"><div class="card-header"><div><h2>Movimientos actuales</h2><p>Ingresos: <?=h(money($summary['ing']))?> · Egresos: <?=h(money($summary['out']))?></p></div></div><?php if($mov):?><div class="table-wrap responsive"><table><thead><tr><th>Fecha</th><th>Tipo</th><th>Método</th><th>Monto</th><th>Detalle</th><th>Usuario</th></tr></thead><tbody><?php foreach($mov as $m):?><tr><td class="primary-cell"><strong><?=h(date_ar($m['created_at'],true))?></strong></td><td data-label="Tipo"><span class="badge <?=$m['type']==='ingreso'?'success':'danger'?>"><?=h(ucfirst($m['type']))?></span></td><td data-label="Método"><?=h(payment_method_label($m['method']))?></td><td data-label="Monto"><strong><?=h(money($m['amount']))?></strong></td><td data-label="Detalle"><?=h($m['description'])?></td><td data-label="Usuario"><?=h($m['user_name']?:'Sistema')?></td></tr><?php endforeach;?></tbody></table></div><?php else:?><p class="muted">No hay movimientos.</p><?php endif;?></section>
<section class="card span12"><div class="card-header"><div><h2>Historial de cierres</h2></div></div><div class="table-wrap responsive"><table><thead><tr><th>Fecha</th><th>Apertura</th><th>Inicial</th><th>Cierre</th><th>Contado</th><th>Abrió / cerró</th></tr></thead><tbody><?php foreach($history as $hrow):?><tr><td class="primary-cell"><strong><?=h(date_ar($hrow['opened_at'],true))?></strong></td><td data-label="Estado"><?=h(ucfirst($hrow['status']))?></td><td data-label="Inicial"><?=h(money($hrow['opening_amount']))?></td><td data-label="Cierre"><?=h(date_ar($hrow['closed_at'],true))?></td><td data-label="Contado"><?=h($hrow['closing_amount']===null?'—':money($hrow['closing_amount']))?></td><td data-label="Personal"><?=h($hrow['opened_name'].' / '.($hrow['closed_name']?:'—'))?></td></tr><?php endforeach;?></tbody></table></div></section></div><?php include 'partials/footer.php';?>
