<?php
require_once 'config.php'; require_role(['admin','recepcion']); ensure_schema(); $pdo=db(); $pageTitle='Reportes';
$from=$_GET['from']??date('Y-m-01');$to=$_GET['to']??date('Y-m-d');if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$from))$from=date('Y-m-01');if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$to))$to=date('Y-m-d');
$st=$pdo->prepare('SELECT COUNT(*) orders,COALESCE(SUM(total_final),0) final_total,COALESCE(SUM(total_estimated),0) estimated FROM work_orders WHERE DATE(created_at) BETWEEN ? AND ?');$st->execute([$from,$to]);$kpi=$st->fetch();
$st=$pdo->prepare('SELECT COALESCE(SUM(amount),0) paid FROM payments WHERE DATE(paid_at) BETWEEN ? AND ?');$st->execute([$from,$to]);$paid=(int)$st->fetchColumn();
$st=$pdo->prepare('SELECT method,COALESCE(SUM(amount),0) total,COUNT(*) count FROM payments WHERE DATE(paid_at) BETWEEN ? AND ? GROUP BY method ORDER BY total DESC');$st->execute([$from,$to]);$methods=$st->fetchAll();
$st=$pdo->prepare('SELECT current_status,COUNT(*) total FROM work_orders WHERE DATE(created_at) BETWEEN ? AND ? GROUP BY current_status ORDER BY total DESC');$st->execute([$from,$to]);$statuses=$st->fetchAll();
$st=$pdo->prepare('SELECT p.name,SUM(bi.quantity) qty,SUM(bi.quantity*bi.unit_price) total FROM budget_items bi JOIN parts p ON p.id=bi.part_id WHERE bi.created_at BETWEEN CONCAT(?," 00:00:00") AND CONCAT(? ," 23:59:59") GROUP BY p.id,p.name ORDER BY qty DESC LIMIT 15');$st->execute([$from,$to]);$parts=$st->fetchAll();
include 'partials/header.php';?><div class="page-head"><div class="page-head-copy"><h1>Reportes</h1><p>Resumen operativo y financiero por período.</p></div></div><section class="card"><form class="toolbar"><label class="field"><span>Desde</span><input type="date" name="from" value="<?=h($from)?>"></label><label class="field"><span>Hasta</span><input type="date" name="to" value="<?=h($to)?>"></label><button class="btn btn-primary">Aplicar</button></form></section><div class="grid"><section class="card span3 kpi-card"><span class="kpi-label">Órdenes</span><div class="kpi"><?=h($kpi['orders'])?></div><div class="kpi-foot">Creadas en el período</div></section><section class="card span3 kpi-card"><span class="kpi-label">Estimado</span><div class="kpi"><?=h(money($kpi['estimated']))?></div><div class="kpi-foot">Presupuestos acumulados</div></section><section class="card span3 kpi-card"><span class="kpi-label">Final</span><div class="kpi"><?=h(money($kpi['final_total']))?></div><div class="kpi-foot">Total final de órdenes</div></section><section class="card span3 kpi-card"><span class="kpi-label">Cobrado</span><div class="kpi"><?=h(money($paid))?></div><div class="kpi-foot">Pagos registrados</div></section>
<section class="card span6"><div class="card-header"><div><h2>Pagos por método</h2></div></div><?php if($methods):?><div class="timeline"><?php foreach($methods as $m):?><div class="event"><strong><?=h(payment_method_label($m['method']))?></strong><small class="muted"><?=h($m['count'])?> pagos</small><p><?=h(money($m['total']))?></p></div><?php endforeach;?></div><?php else:?><p class="muted">Sin pagos.</p><?php endif;?></section>
<section class="card span6"><div class="card-header"><div><h2>Órdenes por estado</h2></div></div><div class="timeline"><?php foreach($statuses as $stt):?><div class="event"><strong><?=h($stt['current_status'])?></strong><span class="badge <?=h(status_tone($stt['current_status']))?>"><?=h($stt['total'])?></span></div><?php endforeach;?></div></section>
<section class="card span12"><div class="card-header"><div><h2>Repuestos más utilizados</h2></div></div><div class="table-wrap responsive"><table><thead><tr><th>Repuesto</th><th>Cantidad</th><th>Importe</th></tr></thead><tbody><?php foreach($parts as $p):?><tr><td class="primary-cell"><strong><?=h($p['name'])?></strong></td><td data-label="Cantidad"><?=h($p['qty'])?></td><td data-label="Importe"><?=h(money($p['total']))?></td></tr><?php endforeach;?></tbody></table></div></section></div><?php include 'partials/footer.php';?>
