<?php
require_once 'config.php'; require_auth(); ensure_schema(); $pdo=db(); $pageTitle='Búsqueda global'; $q=trim((string)($_GET['q']??'')); $clients=[];$vehicles=[];$orders=[];$parts=[];
if($q!==''){ $like='%'.$q.'%'; $st=$pdo->prepare('SELECT id,name,phone,dni FROM clients WHERE active=1 AND (name LIKE ? OR phone LIKE ? OR dni LIKE ?) ORDER BY name LIMIT 20');$st->execute([$like,$like,$like]);$clients=$st->fetchAll();
$st=$pdo->prepare('SELECT v.*,c.name client_name FROM vehicles v JOIN clients c ON c.id=v.client_id WHERE v.active=1 AND (v.plate LIKE ? OR v.engine_number LIKE ? OR v.chassis_number LIKE ? OR v.brand LIKE ? OR v.model LIKE ?) ORDER BY v.brand,v.model LIMIT 20');$st->execute([$like,$like,$like,$like,$like]);$vehicles=$st->fetchAll();
$st=$pdo->prepare('SELECT wo.id,wo.code,wo.current_status,c.name client_name,v.brand,v.model,v.plate FROM work_orders wo JOIN clients c ON c.id=wo.client_id JOIN vehicles v ON v.id=wo.vehicle_id WHERE wo.code LIKE ? OR c.name LIKE ? OR v.plate LIKE ? OR v.engine_number LIKE ? OR v.chassis_number LIKE ? ORDER BY wo.updated_at DESC LIMIT 30');$st->execute([$like,$like,$like,$like,$like]);$orders=$st->fetchAll();
$st=$pdo->prepare('SELECT id,name,sku,stock,sell_price FROM parts WHERE active=1 AND (name LIKE ? OR sku LIKE ? OR category LIKE ?) ORDER BY name LIMIT 20');$st->execute([$like,$like,$like]);$parts=$st->fetchAll(); }
include 'partials/header.php'; ?>
<div class="page-head"><div class="page-head-copy"><h1>Buscar en todo el taller</h1><p>Cliente, teléfono, patente, motor, chasis, orden o repuesto.</p></div></div>
<section class="card"><form class="toolbar"><input class="search" name="q" autofocus placeholder="Ej: ABC123, Juan Pérez, LM-261007..." value="<?=h($q)?>"><button class="btn btn-primary">Buscar</button></form></section>
<?php if($q===''):?><section class="card empty-state"><div><div class="empty-icon">⌕</div><h2>Escribí qué querés encontrar</h2></div></section><?php else:?><div class="grid">
<?php $groups=[['Clientes',$clients,'client_view.php'],['Motos',$vehicles,'client_view.php'],['Órdenes',$orders,'order_view.php'],['Repuestos',$parts,'parts.php']]; foreach($groups as [$title,$rows,$url]):?><section class="card span6"><div class="card-header"><div><h2><?=h($title)?></h2><p><?=count($rows)?> resultado<?=count($rows)==1?'':'s'?></p></div></div><?php if(!$rows):?><p class="muted">Sin resultados.</p><?php else:?><div class="timeline"><?php foreach($rows as $r):?><div class="event"><strong><?php if($title==='Clientes'):?><a href="client_view.php?id=<?=(int)$r['id']?>"><?=h($r['name'])?></a><?php elseif($title==='Motos'):?><a href="client_view.php?id=<?=(int)$r['client_id']?>"><?=h($r['brand'].' '.$r['model'])?></a><?php elseif($title==='Órdenes'):?><a href="order_view.php?id=<?=(int)$r['id']?>"><?=h($r['code'])?></a><?php else:?><a href="parts.php?view=<?=(int)$r['id']?>"><?=h($r['name'])?></a><?php endif;?></strong><small class="muted"><?php if($title==='Clientes'):?><?=h($r['phone'])?> · <?=h($r['dni']?:'Sin DNI')?><?php elseif($title==='Motos'):?><?=h($r['plate'])?> · <?=h($r['client_name'])?><?php elseif($title==='Órdenes'):?><?=h($r['client_name'].' · '.$r['brand'].' '.$r['model'].' · '.$r['plate'])?><?php else:?><?=h(($r['sku']?:'Sin SKU').' · Stock '.units($r['stock']).' · '.money($r['sell_price']))?><?php endif;?></small></div><?php endforeach;?></div><?php endif;?></section><?php endforeach;?></div><?php endif;?><?php include 'partials/footer.php'; ?>
