<?php require_once 'config.php'; $t=$_GET['t']??''; $pdo=db();
$st=$pdo->prepare('SELECT wo.*,c.name client_name,c.phone,v.brand,v.model,v.plate,v.color,v.km FROM work_orders wo JOIN clients c ON c.id=wo.client_id JOIN vehicles v ON v.id=wo.vehicle_id WHERE public_token=?'); $st->execute([$t]); $o=$st->fetch();
if(!$o){ http_response_code(404); die('Seguimiento no encontrado'); }
$updates=$pdo->prepare('SELECT * FROM order_updates WHERE order_id=? AND visible_client=1 ORDER BY created_at DESC'); $updates->execute([$o['id']]); $updates=$updates->fetchAll();
include 'partials/header.php'; ?>
<div class="grid"><section class="card span12"><h1>Seguimiento de tu moto</h1><p class="muted">Lopez Motos mantiene informado cada avance importante de la reparación.</p></section>
<section class="card span6"><h2><?=h($o['brand'].' '.$o['model'])?></h2><p>Patente: <b><?=h($o['plate'] ?: 'No cargada')?></b></p><p>Color: <?=h($o['color'] ?: '-')?> · Km: <?=h($o['km'] ?: '-')?></p><p>Orden: <b><?=h($o['code'])?></b></p><p>Estado actual:</p><div class="kpi"><?=h($o['current_status'])?></div><?php if($o['estimated_delivery']):?><p>Fecha estimada: <b><?=h($o['estimated_delivery'])?></b></p><?php endif;?></section>
<section class="card span6"><h2>Diagnóstico</h2><p><?=nl2br(h($o['diagnosis'] ?: 'Todavía no se cargó un diagnóstico final.'))?></p><h2>Presupuesto estimado</h2><div class="kpi">$<?=number_format((float)$o['total_estimated'],2,',','.')?></div><p><a class="btn good" target="_blank" href="<?=h(wa_link($o['phone'],'Hola Lopez Motos, consulto por mi orden '.$o['code']))?>">Consultar por WhatsApp</a></p></section>
<section class="card span12"><h2>Últimas actualizaciones</h2><div class="timeline"><?php foreach($updates as $u):?><div class="event"><b><?=h($u['status'])?></b><br><small class="muted"><?=h($u['created_at'])?></small><p><?=nl2br(h($u['client_message'] ?: 'El taller actualizó el estado de tu moto.'))?></p></div><?php endforeach;?></div></section></div><?php include 'partials/footer.php'; ?>
